language: cpp

compiler :
 - g++

before_install:
 - sudo apt-get install g++-4.9

branches:
  only:
    - master

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make

os:
 - linux
